test_params = [
    (1, "John Doe", "A brave hero", "active", "male", 1, True),
    (2, "Jane Smith", "A powerful wizard", "inactive", "female", 0, True),
    (3, "Alice", "", "active", "female", 1, True),
    (4, "Bob", "A character with special characters: @#$%^&*()_+{}[]:;<>,.?/", "active", "unknown", -1, True),
    (5, "Chad", "Short description", "inactive", "other", 1, True),
    (6, "Eve", "Long description" * 10, "active", "other", 0, True),
    (7, "Laura", "A description with --SQL Injection", "inactive", "female", 0, True),
    (8, "Mike", "A description with XSS Attack: <script>attack</script>", "active", "unknown", -1, True),
    (9, "Zoe", "A name with @#$%^&*()_+{}[]:;<>,.?/", "inactive", "other", 1, True),
    (10, "Walter", "A name with --SQL Injection", "active", "male", 1, True),
    (11, "Victor", "A name with XSS Attack: <script>attack</script>", "inactive", "unknown", -1, True),
    (12, "Finn", "LongName" * 10, "active", "male", 1, True),
    (13, "Olivia", "LongName" * 10, "inactive", "female", 0, True),
    (14, "Sara", "", "inactive", "unknown", -1, True),
    (15, "David", "@#$%^&*()_+{}[]:;<>,.?/", "active", "other", 1, True),
    (16, "Henry", "@#$%^&*()_+{}[]:;<>,.?/" * 10, "active", "unknown", -1, True),
    (17, "Emily", "Special Characters", "@#$%^&*()_+{}[]:;<>,.?/", "unknown", 1, True),
    (18, "Sophia", "Special Characters", "@#$%^&*()_+{}[]:;<>,.?/" * 10, "@#$%^&*()_+{}[]:;<>,.?/" * 10, 0, True),
    (19, "Liam", "LongName" * 10, "active", "@#$%^&*()_+{}[]:;<>,.?/", -1, True),
    (20, "Emma", "LongName" * 10, "inactive", "@#$%^&*()_+{}[]:;<>,.?/" * 10, 1, True),
    (21, "Noah", "", "active", "other", "@#$%^&*()_+{}[]:;<>,.?/" * 10, False),
    (22, "Ava", "A description with --SQL Injection", "inactive", "female", "@#$%^&*()_+{}[]:;<>,.?/" * 10, False),
    (23, "William", "A description with XSS Attack: <script>attack</script>", "active", "unknown", -1, True),
    (24, "Isabella", "A name with @#$%^&*()_+{}[]:;<>,.?/" * 10, "inactive", "other", 1, False),
    (25, "James", "A name with --SQL Injection", "active", "@#$%^&*()_+{}[]:;<>,.?/" * 10, -1, True),
    (26, "Mia", "A name with XSS Attack: <script>attack</script>", "inactive", "unknown", -1, True),
    (27, "Sophie", "A description with XSS Attack: <script>attack</script>", "inactive", "female", 0, True),
    (28, "Lucas", "A name with @#$%^&*()_+{}[]:;<>,.?/" * 10, "active", "male", 1, False),
    (29, "Aiden", "A name with --SQL Injection", "inactive", "other", -1, True),
    (30, "Ella", "", "active", "@#$%^&*()_+{}[]:;<>,.?/" * 10, -1, True),
    (31, "Jackson", "LongName" * 10, "inactive", "unknown", 1, True),
    (32, "Avery", "LongName" * 10, "active", "male", 0, True),
    (33, "Evelyn", "", "other", "@#$%^&*()_+{}[]:;<>,.?/" * 10, -1, True),
    (34, "Mason", "A description with --SQL Injection", "unknown", "female", -1, True),
    (35, "Scarlett", "A description with XSS Attack: <script>attack</script>", "active", "@#$%^&*()_+{}[]:;<>,.?/" * 10,
     -1,
     True),
    (36, "Logan", "A name with @#$%^&*()_+{}[]:;<>,.?/" * 10, "inactive", "male", 1, False),
    (37, "Luna", "A name with --SQL Injection", "other", "other", -1, True),
    (38, "Carter", "A name with XSS Attack: <script>attack</script>", "active", "@#$%^&*()_+{}[]:;<>,.?/" * 10, -1,
     True),
    (39, "Grace", "Short description", "inactive", "unknown", 0, True),
    (40, "Henry", "Long description" * 100, "active", "male", 1, False),
    (41, "Madison", "A description with --SQL Injection", "unknown", "female", -1, True),
    (42, "Leo", "A description with XSS Attack: <script>attack</script>", "active", "@#$%^&*()_+{}[]:;<>,.?/" * 10, -1,
     True),
    (43, "Michael", "A name with @#$%^&*()_+{}[]:;<>,.?/" * 10, "inactive", "male", 1, False),
    (44, "Aria", "A name with --SQL Injection", "unknown", "other", -1, True),
    (
    45, "Ethan", "A name with XSS Attack: <script>attack</script>", "active", "@#$%^&*()_+{}[]:;<>,.?/" * 10, -1, True),
    (46, "Ariana", "Special Characters", "@#$%^&*()_+{}[]:;<>,.?/", "@#$%^&*()_+{}[]:;<>,.?/", 1, True),
    (47, "Matthew", "Special Characters", "@#$%^&*()_+{}[]:;<>,.?/" * 10, "@#$%^&*()_+{}[]:;<>,.?/" * 10, 0, True),
    (48, "Camila", "LongName" * 10, "active", "@#$%^&*()_+{}[]:;<>,.?/" * 10, -1, True),
    (49, "Daniel", "LongName" * 100, "inactive", "other", 1, False),
    (50, "Penelope", "", "other", "@#$%^&*()_+{}[]:;<>,.?/" * 10, -1, True),
    (51, None, "A brave hero", "active", "male", 1, False),
    (52, "Jane Smith", None, "inactive", "female", 0, True),
    (53, "Alice", "A character with special characters: @#$%^&*()_+{}[]:;<>,.?/", None, "unknown", -1, False),
    (54, "Bob", "Short name character", "active", None, 1, True),
    (55, "LongName" * 100, "A very long name character", "active", "other", None, False),
    (56, "@#$%^&*()_+{}[]:;<>,.?/", "Special Characters", "active", "other", 1, True),
    (57, "Special Characters", "@#$%^&*()_+{}[]:;<>,.?/", "@#$%^&*()_+{}[]:;<>,.?/", None, 1, True),
    (58, "LongName" * 100, "Very long description" * 100, "inactive", "unknown", None, False),
    (59, "--SQL Injection", "Character with SQL injection--", None, "female", 0, False),
    (60, "<>XSS Attack", "XSS <script>attack</script>", "active", None, -1, True),
    (61, 123, "A character with invalid data type", "active", "male", 1, True),
    (62, "John Doe", 123, "inactive", "female", 0, True),
    (63, "Alice", "A character with special characters: @#$%^&*()_+{}[]:;<>,.?/", 123, "unknown", -1, True),
    (64, 123, "@#$%^&*()_+{}[]:;<>,.?/", "active", "other", 1, True),
    (65, "Special Characters", "@#$%^&*()_+{}[]:;<>,.?/", "@#$%^&*()_+{}[]:;<>,.?/", "unknown", 1, True),
    (66, 123, "A description with invalid data type", "active", "female", 0, True),
    (67, "<>XSS Attack", 123, "active", None, -1, True),
    (68, "LongName" * 100, "A very long name character", 123, "other", None, False),
    (69, None, None, None, None, None, False),
    (70, None, "A character with special characters: @#$%^&*()_+{}[]:;<>,.?/", 123, "unknown", -1, False),
    (71, "Special Characters", 123, "@#$%^&*()_+{}[]:;<>,.?/", "@#$%^&*()_+{}[]:;<>,.?/", 1, True),
    (72, 123, None, "@#$%^&*()_+{}[]:;<>,.?/", "other", 1, True),
    (73, "LongName" * 100, "Very long description" * 100, None, "unknown", None, False),
    (74, None, "Character with SQL injection--", "active", None, 0, False),
    (75, 123, 123, 123, 123, 123, True),
    (76, "<>XSS Attack", None, None, "unknown", None, False),
    (77, "", "", "", "", "", False),
    (78, " ", " ", " ", " ", " ", False),
    (79, "  ", "  ", "  ", "  ", "  ", False),
    (80, "\t", "\t", "\t", "\t", "\t", False),
    (81, "\n", "\n", "\n", "\n", "\n", False),
    (82, "John Doe", "", "active", "male", 1, True),
    (83, "", "A powerful wizard", "inactive", "female", 0, False),
    (84, "Alice", "A character with special characters: @#$%^&*()_+{}[]:;<>,.?/", "", "unknown", -1, False),
    (85, "Bob", "Short name character", "", None, 1, False),
    (86, "LongName" * 100, "", "active", "other", None, False),
    (87, "@#$%^&*()_+{}[]:;<>,.?/", "", "active", "other", 1, True),
    (88, "Special Characters", "@#$%^&*()_+{}[]:;<>,.?/", "@#$%^&*()_+{}[]:;<>,.?/", "", 1, True),
    (89, 123, "@#$%^&*()_+{}[]:;<>,.?/", "active", "other", None, False),
    (90, "Special Characters", 123, "@#$%^&*()_+{}[]:;<>,.?/", "@#$%^&*()_+{}[]:;<>,.?/", None, False),
    (91, None, "A description with invalid data type", 123, "female", 0, False),
    (92, "<>XSS Attack", 123, "active", None, None, False),
    (93, 123, "A very long name character", "active", "other", None, False),
    (94, "John Doe", None, "active", "male", 1, True),
    (95, None, "A powerful wizard", "inactive", "female", 0, False),
    (96, "Bob", "Short name character", "active", None, None, False),
    (97, "LongName" * 100, "", "active", "other", None, False),
    (98, "Special Characters", "@#$%^&*()_+{}[]:;<>,.?/", "@#$%^&*()_+{}[]:;<>,.?/", "unknown", None, False),
    (99, 123, "@#$%^&*()_+{}[]:;<>,.?/", "active", "other", None, False),
    (100, "Special Characters", 123, "@#$%^&*()_+{}[]:;<>,.?/", "@#$%^&*()_+{}[]:;<>,.?/", None, False),
]
